--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: cities; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.cities (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    lat real,
    lng real,
    name character varying(255),
    update_at timestamp(6) without time zone
);


ALTER TABLE public.cities OWNER TO admin;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collects; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.collects (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    date timestamp(6) without time zone,
    update_at timestamp(6) without time zone,
    city_id bigint
);


ALTER TABLE public.collects OWNER TO admin;

--
-- Name: collects_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.collects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255),
    role character varying(255),
    updated_at timestamp(6) without time zone,
    city_id bigint,
    user_id bigint
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: waste_types; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.waste_types (
    id bigint NOT NULL,
    class_name character varying(255),
    label character varying(255),
    value character varying(255)
);


ALTER TABLE public.waste_types OWNER TO admin;

--
-- Name: waste_types_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.waste_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.waste_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cities; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.cities (id, created_at, lat, lng, name, update_at) FROM stdin;
1	2025-05-25	48.8566	2.3522	Paris	\N
2	2025-05-25	43.2965	5.3698	Marseille	\N
3	2025-05-25	45.7578	4.832	Lyon	\N
4	2025-05-25	43.6047	1.4442	Toulouse	\N
5	2025-05-25	43.7102	7.262	Nice	\N
6	2025-05-25	47.2184	-1.5536	Nantes	\N
7	2025-05-25	48.5734	7.7521	Strasbourg	\N
\.


--
-- Data for Name: collects; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.collects (id, created_at, date, update_at, city_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (id, created_at, email, first_name, last_name, password, role, updated_at, city_id, user_id) FROM stdin;
1	2025-05-25	monica.geller@test.fr	Monica	Geller	test1234	volunteer	\N	1	\N
2	2025-05-26	rachel.green@test.fr	Rachel	Green	test1234	volunteer	\N	3	\N
3	2025-05-26	phoebe.buffay@test.fr	Phoebe	Buffay	test1234	volunteer	\N	2	\N
4	2025-05-27	joey.tribbiani@test.fr	Joey	Tribbiani	test1234	admin	\N	3	\N
5	2025-05-29	chandler.bing@test.fr	Chandler	Bing	test1234	volunteer	\N	4	\N
6	2025-05-30	ross.geller@test.fr	Ross	Geller	test1234	volunteer	\N	5	\N
\.


--
-- Data for Name: waste_types; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.waste_types (id, class_name, label, value) FROM stdin;
1	badge-cigarette	Cigarette butts	cigarette
2	badge-plastic	Plastic	plastic
3	badge-glass	Glass	glass
4	badge-metal	Metal	metal
5	badge-electronic	Electronic	electronic
6	badge-other	Other	other
\.


--
-- Name: cities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.cities_id_seq', 7, true);


--
-- Name: collects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.collects_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 6, true);


--
-- Name: waste_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.waste_types_id_seq', 6, true);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: collects collects_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.collects
    ADD CONSTRAINT collects_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: waste_types waste_types_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.waste_types
    ADD CONSTRAINT waste_types_pkey PRIMARY KEY (id);


--
-- Name: collects fkb99e5cbiop2gchpw22mrshydm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.collects
    ADD CONSTRAINT fkb99e5cbiop2gchpw22mrshydm FOREIGN KEY (city_id) REFERENCES public.cities(id);


--
-- Name: users fkhdb2dt1rc2gqr2j91bybemgj0; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkhdb2dt1rc2gqr2j91bybemgj0 FOREIGN KEY (user_id) REFERENCES public.collects(id);


--
-- Name: users fkn36jwt4acj3il2ixvv2c0ncco; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkn36jwt4acj3il2ixvv2c0ncco FOREIGN KEY (city_id) REFERENCES public.cities(id);


--
-- Name: DATABASE db_trashzilla; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON DATABASE db_trashzilla TO admin;


--
-- PostgreSQL database dump complete
--
